### ISSUE TITLE
Invalid Locale error

### ISSUE THREAD

**Issue by vaishsree** [mageplaza/magento-2-chinese-language-pack#2]
Below error occurs while following exception after executing php bin/magento setup:static-content:deploy zh_CN

[InvalidArgumentException]
zh_CN argument has invalid value, please run info:language:list for list of available locales

setup:static-content:deploy [-d|--dry-run] [--no-javascript] [--no-css] [--no-less] [--no-images] [--no-fon ts] [--no-html] [--no-misc] [--no-html-minify] [-t|--theme[="..."]] [--exclude-
theme[="..."]] [-l|--languag e[="..."]] [--exclude-language[="..."]] [-a|--area[="..."]] [--exclude-area[="..."]] [-j|--jobs[="..."]] [- -symlink-locale] [languages1] ... [languagesN]

Please help.

**Comment by gilles6** [comment]
There's an error in this command, it shoud be:
`php bin/magento setup:static-content:deploy zh_Hans_CN`

**Comment by gilles6** [comment]
This repository is actually not working because of wrong language code. You can use this one instead:
https://github.com/Magento2Translations/language_zh_hans_cn

**Comment by imsamthomas** [comment]
We fixed the issue, see https://github.com/mageplaza/magento-2-chinese-language-pack

**Comment by imsamthomas** [comment]
P/s: Screenshot 

![screenshot](http://i.imgur.com/urYP0D5.png)
