### ISSUE TITLE
Add version tag

### ISSUE THREAD

**Issue by sippsolutions** [mageplaza/magento-2-chinese-language-pack#8]
See #7 - the fixed version was removed from composer.json, but no release was pushed.
Please add a tag "1.0.2" via Github or via "git checkout master; git pull; git tag 1.0.2; git push --tags" on command line.

**Comment by legendhorus** [comment]
I have added the tag version. Please check it again

**Comment by sippsolutions** [comment]
@myodaisy cool! 😎
